#!/bin/sh
# Since Tup refuses to depend on files inside `.git/`…

version_fn="obj/version.h"
version_tag="(unknown)"

if [ -d .git ]; then
	{
		[ ".git/HEAD" -ot "$version_fn" ] &&
		[ ".git/refs/tags" -ot "$version_fn" ] &&
		[ "$0" -ot "$version_fn" ];
	} && exit 0;

	tag=$(git tag --points-at HEAD)

	if ! { git diff-files --quiet && [ -n "$tag" ]; }; then
		desc=$(git describe --tags --abbrev=0)
		commit=$(git rev-parse --short=4 HEAD)
		version_tag="WIP ("$desc"^"$commit")"
	else
		version_tag="$tag"
	fi
fi

mkdir -p $(dirname "$version_fn")
 >$version_fn echo // Generated by \`"$0"\`.
>>$version_fn echo \#define VERSION_TAG \"$version_tag\"
