/*                                                                           */
/*   GIAN.cpp   ゲーム全体の管理                                             */
/*                                                                           */
/*                                                                           */

#include "GIAN.H"


///// [グローバル変数] /////
uint32_t	GameCount;
uint8_t	GameStage;
