/*                                                                           */
/*   DX_TYPE.h   ＤＸ関連の定数とか                                          */
/*                                                                           */
/*                                                                           */

#ifndef PBGWIN_DX_TYPE_H
#define PBGWIN_DX_TYPE_H		"DX_TYPE : Version 0.02"


// 更新履歴 //

// 2000/05/15 : 関数呼び出し規約 FINT 等を追加
// 2000/01/30 : バージョン文字列を出力するようにした
// 1999/12/02 : ＤＤ＿ＵＴＹから分離する


// ヘッダファイル //
#include <windows.h>
#include <stdio.h>


// ヘッダファイルのバージョンを表示する //
#pragma message("-----[" PBGWIN_DX_TYPE_H " / " __TIMESTAMP__ "]-----")
#pragma message("------------------------------")


#endif
