/*
 *   Unused laser code
 *
 */

const int laser_color[16] ={
		RGB256(0,0,3),RGB256(0,4,0),RGB256(0,3,3),RGB256(3,0,0),
		RGB256(3,0,3),RGB256(3,3,0),RGB256(3,3,3),
		RGB256(0,0,5),RGB256(0,5,0),RGB256(0,5,5),RGB256(5,0,0),
		RGB256(5,0,5),RGB256(5,5,0),RGB256(5,5,5)
};

////グローバル変数////
//REFLECTOR		Reflector[RT_MAX];					// 反射物_構造体
//WORD			ReflectorNow;						// 反射物の個数

static int  __fastcall REFL_hit(LASER_DATA *lp)
{
	//REFLECTOR *rp;
}
